included:
  - SampleProjectSwiftUI
  - Utilities
  - DataProvider
  - UIComponents
excluded:
  - .git
analyzer_rules:
  - unused_declaration
  - unused_import
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - sorted_imports
  - multiple_closures_with_trailing_closure
  - unneeded_parentheses_in_closure_argument
  - strong_iboutlet
  - prohibited_interface_builder
  - modifier_order
  - file_header
  - pattern_matching_keywords
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

identifier_name:
  excluded:
    - id

number_separator:
  minimum_length: 5

line_length:
  - 150 #warning
  - 200 #error

custom_rules:
  fatal_error:
    name: Fatal Error
    excluded: "Tests/*"
    message: Prefer using `queuedFatalError` over `fatalError` to avoid leaking compiler host machine paths.
    regex: \bfatalError\b
    match_kinds:
      - identifier
    severity: error
